export const rotatingTextWords = [
  "React",
  "Next JS",
  "Typescript",
  "Javascript",
  "Node JS",
  "Tailwind",
  "Figma",
]

export const SeoKeyWords = [
  "express",
  "node js",
  "react",
  "next",
  "tailwind",
  "styled component",
  "css",
  "scss",
  "react hooks",
  "custom hooks",
  "figma",
  "design",
  "prisma",
  "git",
  "github",
  "javascript",
  "typescript",
  "docker",
  "linux",
  "windows",
  "frontend",
  "fullstack",
  "web development",
  "frontend development",
  "backend development",
  "responsive design",
  "ui/ux design",
  "component library",
  "state management",
  "context api",
  "redux",
  "zustand",
  "rest api",
  "graphql",
  "apollo client",
  "server-side rendering",
  "static site generation",
  "ssr",
  "ssg",
  "ci/cd",
  "continuous integration",
  "deployment",
  "npm",
  "yarn",
  "pnpm",
  "version control",
  "agile methodology",
  "storybook",
  "accessibility",
  "performance optimization",
  "seo",
  "search engine optimization",
  "progressive web app",
  "pwa",
  "mobile-first design",
  "prototyping",
  "mockups",
  "wireframes",
  "user experience",
  "user interface",
  "open source",
  "api integration",
  "database management",
  "postgresql",
  "mysql",
  "mongodb",
  "nosql",
  "orm",
  "middleware",
  "jwt",
  "motion design",
  "animation",
  "framer motion",
  "static websites",
  "dynamic websites",
  "web performance",
  "lazy loading",
  "bundle optimization",
  "webpack",
  "vite",
  "esbuild",
  "eslint",
  "Portfolio",
  "LinkedIn",
  "GitHub",
  "Instagram",
  "desenvolvedor",
  "designer",
]
