export const rotatingTextValues = [
  "React",
  "Next JS",
  "Typescript",
  "Javascript",
  "Node JS",
  "Tailwind",
  "Figma",
]

export const projectKeyWords = [
  "express",
  "node js",
  "react",
  "next",
  "tailwind",
  "styled component",
  "css",
  "scss",
  "react hooks",
  "custom hooks",
  "figma",
  "design",
  "prisma",
  "git",
  "github",
  "javascript",
  "typescript",
  "docker",
  "linux",
  "windows",
  "frontend",
  "fullstack",
  "web development",
  "frontend development",
  "backend development",
  "responsive design",
  "ui/ux design",
  "component library",
  "state management",
  "context api",
  "redux",
  "zustand",
  "rest api",
  "graphql",
  "apollo client",
  "server-side rendering",
  "static site generation",
  "ssr",
  "ssg",
  "ci/cd",
  "continuous integration",
  "deployment",
  "aws",
  "azure",
  "cloud computing",
  "containerization",
  "kubernetes",
  "npm",
  "yarn",
  "pnpm",
  "version control",
  "code review",
  "agile methodology",
  "devops",
  "testing",
  "jest",
  "react testing library",
  "cypress",
  "storybook",
  "accessibility",
  "performance optimization",
  "seo",
  "search engine optimization",
  "progressive web app",
  "pwa",
  "mobile-first design",
  "prototyping",
  "mockups",
  "wireframes",
  "user experience",
  "user interface",
  "team collaboration",
  "open source",
  "api integration",
  "database management",
  "postgresql",
  "mysql",
  "mongodb",
  "nosql",
  "orm",
  "schema design",
  "middleware",
  "authentication",
  "authorization",
  "jwt",
  "oauth",
  "microservices",
  "monorepo",
  "lerna",
  "nx",
  "bash scripting",
  "terminal commands",
  "shell scripting",
  "virtual machines",
  "cross-platform development",
  "web accessibility standards",
  "wcag",
  "motion design",
  "animation",
  "framer motion",
  "webgl",
  "data visualization",
  "chart.js",
  "d3.js",
  "real-time applications",
  "socket.io",
  "websocket",
  "headless cms",
  "contentful",
  "sanity",
  "strapi",
  "jamstack",
  "static websites",
  "dynamic websites",
  "web performance",
  "lazy loading",
  "code splitting",
  "tree shaking",
  "bundle optimization",
  "webpack",
  "vite",
  "esbuild",
  "eslint",
]
