import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import NavBar from "./components/NavBar";
import "./globals.css";

const robotoFont = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Paulo Victor | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="shortcut icon" href="/favicon.svg" type="image/x-icon" />
      </head>
      <body className={`${robotoFont.className}  antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
